### PR TITLE
Xmas quest

### PR DESCRIPTION
**Pull request by danigm**
This is an initial version of the quest for christmas. This quest depends on:

 * https://github.com/endlessm/hack-toolbox-app/pull/252
 * And the "waiting for review" snow extension: https://extensions.gnome.org/review/21711

The `xmas2020.py` quest does this right now:

 * New auto-offer quest that will be offered automatically during december
 * This quest will appear on the OS pathway
 * This quest requires network
 * The quest ask to the user if he wants to play the quest or not. That's because it's auto-offer, to be able to dismiss it quickly
 * Then it tries to install the "snow" extension. It's not published yet, so this step will fail. For testing you can install the extension by hand from here: https://extensions.gnome.org/review/download/21711.shell-extension.zip and make sure to disable before run the quest, because the quest will guide you to enable it
 * The next step is to install the `org.gnome.Extensions` app
 * Once the extensions app is installed the quest guides the user to enable the "snow" extension
 * Then it guides the user to use the Flip to Hack and play around with controls. We can't detect that the app is flipped because there's no clippy integration here
 * Then talk about emojis
 * The last step is to talk about css modifications

Maybe the css color modification at the end, need some changes because if the user changes the emoji and use some with colors, the `color` change does nothing. Maybe we should tell the user to set the default snowflake before.

https://phabricator.endlessm.com/T31164

### CODE REVIEW

**Comment by bkarnow** [comment]
I'll review the text for this first thing on Friday

**Comment by bkarnow** [comment]
Initial text edits are in - I'll see if I can get the rest installed and tested before EOD.

**Comment by bkarnow** [comment]
I'm seeing some issues in the CSS portion, all I see in the code window is the below:
Screenshot from 2020-12-15 12-09-23
Other than that, everything seems to be working well. I think, if there's a difficulty here, we can drop the CSS section and keep the rest - it's still got some nice content.

**Comment by danigm** [comment]
> I'm seeing some issues in the CSS portion, all I see in the code window is the below:
> Screenshot from 2020-12-15 12-09-23
> Other than that, everything seems to be working well. I think, if there's a difficulty here, we can drop the CSS section and keep the rest - it's still got some nice content.

There should be something broken on your end, the left icons for "Snow" and "Styles" are broken. I'll try to test thins on EOS 3.9.1 because right now I've done almost all my tests on my ubuntu.

**Pull request merged**
